name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx -p node@lts -c "npx semantic-release"
